//------------------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“VehicleType.cs”的分部类“public partial class VehicleType”}添加属性
// </auto-generated>
//
//  <copyright file="VehicleType.generated.cs">
//      
//  </copyright>
//  <site></site>
//  <last-editor>Jiangyimin</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;


namespace CPS.Dict.Entities
{
    /// <summary>
    /// 实体类：车辆类型信息
    /// </summary>
    [Description("车辆类型信息")]
    public partial class VehicleType : EntityBase<int>, ICreatedTime, IUpdateAudited<int>
    {
        /// <summary>
        /// 获取或设置 序号
        /// </summary>
        [DisplayName("序号"), Required]
        public string Cn { get; set; }

        /// <summary>
        /// 获取或设置 名称
        /// </summary>
        [DisplayName("名称"), Required]
        public string Name { get; set; }

        /// <summary>
        /// 获取或设置 载重
        /// </summary>
        [DisplayName("载重")]
        public int Load { get; set; }

        /// <summary>
        /// 获取或设置 容量
        /// </summary>
        [DisplayName("容量")]
        public int Capacity { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

    }
}

