// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前实体 FieldInputRule 添加方法，可新建文件“DictServiceBase.FieldInputRule.cs”的分部类“public abstract partial class DictServiceBase”添加功能
//      2.纵向扩展：如需要重写当前实体 FieldInputRule 的业务实现，可新建文件“DictService.FieldInputRule.cs”的分部类“public partial class DictService”对现有方法进行方法重写实现
// </auto-generated>
//
//  <copyright file="DictServiceBase.FieldInputRule.generated.cs">
//      
//  </copyright>
//  <site></site>
//  <last-editor>Jiangyimin</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Dependency;
using OSharp.Extensions;
using OSharp.Mapping;

using CPS.Dict.Dtos;
using CPS.Dict.Entities;


namespace CPS.Dict
{
    public abstract partial class DictServiceBase
    {
        /// <summary>
        /// 获取 字段输入规则信息查询数据集
        /// </summary>
        public IQueryable<FieldInputRule> FieldInputRules
        {
            get { return FieldInputRuleRepository.QueryAsNoTracking(); }
        }

        /// <summary>
        /// 检查字段输入规则信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的字段输入规则信息编号</param>
        /// <returns>字段输入规则信息是否存在</returns>
        public virtual Task<bool> CheckFieldInputRuleExists(Expression<Func<FieldInputRule, bool>> predicate, int id = default(int))
        {
            return FieldInputRuleRepository.CheckExistsAsync(predicate, id);
        }
        
        /// <summary>
        /// 添加字段输入规则信息
        /// </summary>
        /// <param name="dtos">要添加的字段输入规则信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> CreateFieldInputRules(params FieldInputRuleInputDto[] dtos)
        {
            Check.Validate<FieldInputRuleInputDto, int>(dtos, nameof(dtos));
            return FieldInputRuleRepository.InsertAsync(dtos);
        }
        
        /// <summary>
        /// 更新字段输入规则信息
        /// </summary>
        /// <param name="dtos">包含更新信息的字段输入规则信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> UpdateFieldInputRules(params FieldInputRuleInputDto[] dtos)
        {
            Check.Validate<FieldInputRuleInputDto, int>(dtos, nameof(dtos));
            return FieldInputRuleRepository.UpdateAsync(dtos);
        }
        
        /// <summary>
        /// 删除字段输入规则信息
        /// </summary>
        /// <param name="ids">要删除的字段输入规则信息编号</param>
        /// <returns>业务操作结果</returns>
        public virtual Task<OperationResult> DeleteFieldInputRules(params int[] ids)
        {
            Check.NotNull(ids, nameof(ids));
            return FieldInputRuleRepository.DeleteAsync(ids);
        }
    }
}
