// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1. 横向扩展：如需给当前模块添加方法接口，可新建文件“IDictContract.cs”的分部接口“public partial interface IDictContract”添加方法，并添加相应新的分部基类 abstract partial class DictServiceBase 实现新方法
// </auto-generated>
//
//  <copyright file="IDictContract.generated.cs">
//      
//  </copyright>
//  <site></site>
//  <last-editor>Jiangyimin</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using OSharp.Data;
using OSharp.Extensions;

using CPS.Dict.Dtos;
using CPS.Dict.Entities;


namespace CPS.Dict
{
    /// <summary>
    /// 业务契约接口：字典管理模块
    /// </summary>
    public partial interface IDictContract
    {
        #region 线路类型信息业务

        /// <summary>
        /// 获取 线路类型信息查询数据集
        /// </summary>
        IQueryable<RouteType> RouteTypes { get; }

        /// <summary>
        /// 检查线路类型信息信息是否存在
        /// </summary>
        /// <param name="predicate">检查谓语表达式</param>
        /// <param name="id">更新的线路类型信息编号</param>
        /// <returns>线路类型信息是否存在</returns>
        Task<bool> CheckRouteTypeExists(Expression<Func<RouteType, bool>> predicate, int id = default(int));
        
        /// <summary>
        /// 添加线路类型信息信息
        /// </summary>
        /// <param name="dtos">要添加的线路类型信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> CreateRouteTypes(params RouteTypeInputDto[] dtos);
            
        /// <summary>
        /// 更新线路类型信息信息
        /// </summary>
        /// <param name="dtos">包含更新信息的线路类型信息DTO信息</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> UpdateRouteTypes(params RouteTypeInputDto[] dtos);
            
        /// <summary>
        /// 删除线路类型信息信息
        /// </summary>
        /// <param name="ids">要删除的线路类型信息编号</param>
        /// <returns>业务操作结果</returns>
        Task<OperationResult> DeleteRouteTypes(params int[] ids);
        

        #endregion
        
    }
}
