// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“FieldInputRuleOutputDto.cs”的分部类“public partial class FieldInputRuleOutputDto”}添加属性
// </auto-generated>
//
//  <copyright file="FieldInputRuleOutputDto.generated.cs">
//      
//  </copyright>
//  <site></site>
//  <last-editor>Jiangyimin</last-editor>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using OSharp.Entity;
using OSharp.Mapping;

using CPS.Dict.Entities;

namespace CPS.Dict.Dtos
{
    /// <summary>
    /// 输入DTO：字段输入规则信息
    /// </summary>
    [MapFrom(typeof(FieldInputRule))]
    [Description("字段输入规则信息")]
    public partial class FieldInputRuleOutputDto : IOutputDto
    {
        /// <summary>
        /// 初始化一个<see cref="FieldInputRuleOutputDto"/>类型的新实例
        /// </summary>
        public FieldInputRuleOutputDto()
        { }

        /// <summary>
        /// 初始化一个<see cref="FieldInputRuleOutputDto"/>类型的新实例
        /// </summary>
        public FieldInputRuleOutputDto(FieldInputRule entity)
        {
            Id = entity.Id;
            EntityName = entity.EntityName;
            FieldName = entity.FieldName;
            Regexp = entity.Regexp;
            CreatedTime = entity.CreatedTime;
            LastUpdaterId = entity.LastUpdaterId;
            LastUpdatedTime = entity.LastUpdatedTime;
        }

        /// <summary>
        /// 获取或设置 编号
        /// </summary>
        [DisplayName("编号")]
        public int Id { get; set; }

        /// <summary>
        /// 获取或设置 实体名称
        /// </summary>
        [DisplayName("实体名称")]
        public string EntityName { get; set; }

        /// <summary>
        /// 获取或设置 字段名称
        /// </summary>
        [DisplayName("字段名称")]
        public string FieldName { get; set; }

        /// <summary>
        /// 获取或设置 正则表达式
        /// </summary>
        [DisplayName("正则表达式")]
        public string Regexp { get; set; }

        /// <summary>
        /// 获取或设置 创建时间
        /// </summary>
        [DisplayName("创建时间")]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// 获取或设置 更新者
        /// </summary>
        [DisplayName("更新者")]
        public int? LastUpdaterId { get; set; }

        /// <summary>
        /// 获取或设置 更新时间
        /// </summary>
        [DisplayName("更新时间")]
        public DateTime? LastUpdatedTime { get; set; }

    }
}
